Repository BuildForSDG/team-132-backend, pull requests merged in 2020-05, with the labels that each got.

#9 Ft Create Farmer API
  .eslintrc.js
  __tests__/integration/farmer.register.test.js
  __tests__/testDb.test.js
  __tests__/unknownRoutes.test.js
  __tests__/utils.js
  api.rest
  jest.config.js
  models/User.js
  package.json
  src/app.js
  src/config/dbConfig.js
  src/config/startServer.js
  src/controllers/farmer.controller.js
  src/models/User.js
  src/routes/farmer.router.js
  src/routes/index.js
  src/server.js
  src/services/farmer.service.js
  src/validator/farmer.validator.js
  yarn.lock
Labels: ready for review

#11 Yarn changes
  yarn.lock
Labels: Chore

#12 Added travis integration
  .travis.yml
  __tests__/testData.test.js
  __tests__/utils.js
  jest.config.js
  package.json
Labels: Chore

#17 ch: updated app-properties file-16
  .travis.yml
  __tests__/testData.test.js
  app.properties
Labels: Chore

#15 feat: added ussd user registration endpoint
  README.md
  __tests__/integration/farmer.register.test.js
  __tests__/integration/farmer.ussd.register.test.js
  __tests__/utilFunctions/helper.test.js
  __tests__/utils.js
  api.rest
  app.properties
  package.json
  src/controllers/ussdFarmerController.js
  src/models/sessionLevel.js
  src/models/ussdUserModel.js
  src/routes/farmer.router.js
  src/routes/index.js
  src/utils/helper/helper.js
  src/utils/helper/ussdHelper.js
  src/validator/farmer.validator.js
  yarn.lock
Labels: feature
